/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as OverlayRouteImport } from './routes/overlay'
import { Route as StudioIndexRouteImport } from './routes/_studio.index'
import { Route as StudioAudioRouteImport } from './routes/_studio.audio'
import { Route as StudioDesignerRouteImport } from './routes/_studio.designer'
import { Route as StudioLibraryRouteImport } from './routes/_studio.library'
import { Route as StudioObsRouteImport } from './routes/_studio.obs'
import { Route as StudioPresetsRouteImport } from './routes/_studio.presets'
import { Route as StudioSettingsRouteImport } from './routes/_studio.settings'
import { Route as ApiLiveRouteImport } from './routes/api/live'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const OverlayRoute = OverlayRouteImport.update({
  id: '/overlay',
  path: '/overlay',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioAudioRoute = StudioAudioRouteImport.update({
  id: '/audio',
  path: '/audio',
  getParentRoute: () => StudioRoute,
} as any)
const StudioDesignerRoute = StudioDesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLibraryRoute = StudioLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudioRoute,
} as any)
const StudioObsRoute = StudioObsRouteImport.update({
  id: '/obs',
  path: '/obs',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPresetsRoute = StudioPresetsRouteImport.update({
  id: '/presets',
  path: '/presets',
  getParentRoute: () => StudioRoute,
} as any)
const StudioSettingsRoute = StudioSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => StudioRoute,
} as any)
const ApiLiveRoute = ApiLiveRouteImport.update({
  id: '/api/live',
  path: '/api/live',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/overlay': typeof OverlayRoute
  '/audio': typeof StudioAudioRoute
  '/designer': typeof StudioDesignerRoute
  '/library': typeof StudioLibraryRoute
  '/obs': typeof StudioObsRoute
  '/presets': typeof StudioPresetsRoute
  '/settings': typeof StudioSettingsRoute
  '/api/live': typeof ApiLiveRoute
}
export interface FileRoutesByTo {
  '/overlay': typeof OverlayRoute
  '/audio': typeof StudioAudioRoute
  '/designer': typeof StudioDesignerRoute
  '/library': typeof StudioLibraryRoute
  '/obs': typeof StudioObsRoute
  '/presets': typeof StudioPresetsRoute
  '/settings': typeof StudioSettingsRoute
  '/api/live': typeof ApiLiveRoute
  '/': typeof StudioIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/overlay': typeof OverlayRoute
  '/_studio/audio': typeof StudioAudioRoute
  '/_studio/designer': typeof StudioDesignerRoute
  '/_studio/library': typeof StudioLibraryRoute
  '/_studio/obs': typeof StudioObsRoute
  '/_studio/presets': typeof StudioPresetsRoute
  '/_studio/settings': typeof StudioSettingsRoute
  '/api/live': typeof ApiLiveRoute
  '/_studio/': typeof StudioIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/overlay'
    | '/audio'
    | '/designer'
    | '/library'
    | '/obs'
    | '/presets'
    | '/settings'
    | '/api/live'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/overlay'
    | '/audio'
    | '/designer'
    | '/library'
    | '/obs'
    | '/presets'
    | '/settings'
    | '/api/live'
    | '/'
  id:
    | '__root__'
    | '/_studio'
    | '/overlay'
    | '/_studio/audio'
    | '/_studio/designer'
    | '/_studio/library'
    | '/_studio/obs'
    | '/_studio/presets'
    | '/_studio/settings'
    | '/api/live'
    | '/_studio/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  OverlayRoute: typeof OverlayRoute
  ApiLiveRoute: typeof ApiLiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overlay': {
      id: '/overlay'
      path: '/overlay'
      fullPath: '/overlay'
      preLoaderRoute: typeof OverlayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/audio': {
      id: '/_studio/audio'
      path: '/audio'
      fullPath: '/audio'
      preLoaderRoute: typeof StudioAudioRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/designer': {
      id: '/_studio/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof StudioDesignerRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/library': {
      id: '/_studio/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof StudioLibraryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/obs': {
      id: '/_studio/obs'
      path: '/obs'
      fullPath: '/obs'
      preLoaderRoute: typeof StudioObsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/presets': {
      id: '/_studio/presets'
      path: '/presets'
      fullPath: '/presets'
      preLoaderRoute: typeof StudioPresetsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/settings': {
      id: '/_studio/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof StudioSettingsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/api/live': {
      id: '/api/live'
      path: '/api/live'
      fullPath: '/api/live'
      preLoaderRoute: typeof ApiLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioRouteChildren {
  StudioAudioRoute: typeof StudioAudioRoute
  StudioDesignerRoute: typeof StudioDesignerRoute
  StudioLibraryRoute: typeof StudioLibraryRoute
  StudioObsRoute: typeof StudioObsRoute
  StudioPresetsRoute: typeof StudioPresetsRoute
  StudioSettingsRoute: typeof StudioSettingsRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioAudioRoute: StudioAudioRoute,
  StudioDesignerRoute: StudioDesignerRoute,
  StudioLibraryRoute: StudioLibraryRoute,
  StudioObsRoute: StudioObsRoute,
  StudioPresetsRoute: StudioPresetsRoute,
  StudioSettingsRoute: StudioSettingsRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  OverlayRoute: OverlayRoute,
  ApiLiveRoute: ApiLiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
